version: '3'

services:
  pokedexapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - '${PORT}:${PORT}'
    # working_dir: /var/www/pokedex
    links:
      - 'db:database'
    environment:
      MONGODB_URL: mongodb://mongo-poke:27017/nest-pokemon #${MONGODB_URL}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    networks:
      - netbackend
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5.0-focal
    container_name: mongo-poke
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    networks:
      - netbackend
    # volumes:
    #   - ./mongo:/data/db

networks:
  netbackend:
    driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.26.238.0/24
    #       gateway: 172.26.238.1
